---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 2080}]
    - ["forwarded_port", {guest: 8443, host: 2443}]
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: recipe[h2o]
    attributes:
