name             'h2o'
maintainer       'Peter Helenefors'
maintainer_email 'peter@hertigcarl.se'
license          'All rights reserved'
description      'Installs/Configures h2o'
long_description 'Installs/Configures h2o'
version          '0.1.0'

depends 'git'
#depends 'cmake'
depends 'apt'